name: Periodic health check
on:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  healthcheck:
    runs-on: ubuntu-20.04
    steps:
      - uses: jtalk/url-health-check-action@v2
        with:
          url: https://fullstack-cicd-pokedex.herokuapp.com/health
          max-attempts: 3 
          follow-redirect: no
          retry-delay: 5s