name: Deploy to Heroku
on:
  workflow_run:
    workflows:
      - Simple pipeline
    branches: [master]
    types:
      - completed
jobs:
  deploy-to-prod:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event_name == 'push' }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "fullstack-cicd-pokedex"
          heroku_email: "matteo.calabrese1@gmail.com"
          healthcheck: "https://fullstack-cicd-pokedex.herokuapp.com/health"
          checkstring: "ok"
          delay: 5
          rollbackonhealthcheckfailed: true
